### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by calemarie** [danielbrendel/hortusfox-web#42]
Dear Daniel,

First of all, thank you so much for your work on Hortusfox - your dedication is impressive, and this piece of software looks like exactly filling a gap in my self-hosting needs! 

# The Bug

I have tried to install Hortusfox following [these instructions](https://github.com/danielbrendel/hortusfox-web#manual-installation), however could not succeed: I stumble on an error when trying to populate the database (asatry migrate:fresh):

```shell
charlie@HomeServices:/opt/hortusfox-web$ php asatru migrate:fresh
PHP Fatal error:  Uncaught Error: Class "CacheModel_Migration" not found in /opt/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/database.php:1145
Stack trace:
#0 /opt/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/database.php(1199): Asatru\Database\MigrationLoader->dropAll()
#1 /opt/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/console.php(1034): migrate_fresh()
#2 /opt/hortusfox-web/asatru(37): Asatru\Console\handleInput()
#3 {main}
  thrown in /opt/hortusfox-web/vendor/danielbrendel/asatru-php-framework/src/database.php on line 1145
``` 

For reference, I cloned the repo in `/opt`, and gave all credentials to user _charlie_ on the `/opt/hortusfox-web` folder

# Server details
### OS Debian 12
```shell
charlie@HomeServices:/opt/hortusfox-web$ uname -a
Linux HomeServices 5.15.131-1-pve #1 SMP PVE 5.15.131-1 (2023-11-09T09:29Z) x86_64 GNU/Linux
```
### PHP v8.2.7
```shell
charlie@HomeServices:/opt/hortusfox-web$ php --version
PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies
```

### MySQL v15.1
MySQL is installed and configured (I manually created user and database for hortusfox):
```shellcharlie@HomeServices:/opt/hortusfox-web$ mysql --version
mysql  Ver 15.1 Distrib 10.11.4-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

### Composer v2.6.6

```shell
charlie@HomeServices:/opt/hortusfox-web$ composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 2.6.6 2023-12-08 18:32:26
```

# Installation details

As far as I can tell, the Installation went smoothly. Here is the detail of the packages installed:

```shell
charlie@HomeServices:/opt/hortusfox-web$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 33 installs, 0 updates, 0 removals
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/type (1.1.4): Extracting archive
  - Installing sebastian/resource-operations (2.0.2): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/global-state (3.0.3): Extracting archive
  - Installing sebastian/exporter (3.1.5): Extracting archive
  - Installing sebastian/environment (4.2.4): Extracting archive
  - Installing sebastian/diff (3.0.4): Extracting archive
  - Installing sebastian/comparator (3.0.5): Extracting archive
  - Installing phpunit/php-timer (2.1.3): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (2.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (4.0.4): Extracting archive
  - Installing phpunit/php-code-coverage (7.0.15): Extracting archive
  - Installing phar-io/version (3.2.1): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.11.1): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.28.0): Extracting archive
  - Installing doctrine/instantiator (1.5.0): Extracting archive
  - Installing phpunit/phpunit (8.5.36): Extracting archive
  - Installing phpmailer/phpmailer (v6.9.1): Extracting archive
  - Installing symfony/translation-contracts (v3.4.0): Extracting archive
  - Installing symfony/deprecation-contracts (v3.4.0): Extracting archive
  - Installing symfony/translation (v6.4.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.28.0): Extracting archive
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing carbonphp/carbon-doctrine-types (3.1.0): Extracting archive
  - Installing nesbot/carbon (2.72.1): Extracting archive
  - Installing danielbrendel/asatru-php-framework (v1.0): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
27 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

# Reproduction steps:

1. Configure server with NGinx, MySQL, PHP and Composer
2. Clone [git repo](https://github.com/danielbrendel/hortusfox-web)
3. Run `composer install` in cloned repo
4. Initialize databases with `php asatru migrate:fresh`

Thanks in advance!

**Comment by danielbrendel** [comment]
Hi, thank you for your bug report and I am glad that you like the product! I just found the issue and this was because I renamed the migration class incorrectly. I'll provide a fix for that.

**Comment by calemarie** [comment]
I am... speechless. Fully solved in a matter of hours. 
Thank you so much Daniel, this is now fixed. 
I admire how quickly you dealt with this. 
Time to explore now!

**Comment by danielbrendel** [comment]
Glad it works now! Have fun and don't hesitate to open another issue if anything else is not working as expected.
