### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by shroomify-it** [danielbrendel/hortusfox-web#60]
Hi Daniel,

I tried installing hortus-web via docker-compose.yml only. The web interface works fine until i add a new plant : 

`
Warning: file_put_contents(/var/www/html/.env): Failed to open stream: Permission denied in /var/www/html/app/modules/UtilsModule.php on line 298

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/app/modules/UtilsModule.php:298) in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/view.php on line 677
`

I then tried to install via git clone + docker build.
It simply does not start :
`
Notice: ob_clean(): Failed to delete buffer. No buffer to delete in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/exception.php on line 21

Fatal error: Uncaught Error: Class "Asatru\View\ViewHandler" not found in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/helper.php:246 Stack trace: #0 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/exception.php(22): view('error/exception...', Array, Array) #1 [internal function]: {closure}(Object(PDOException)) #2 {main} thrown in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/helper.php on line 246
`

Did i miss a step ?
Thank you in advance

**Comment by buzzlightyear88** [comment]
I am getting a similar issue when trying to add a plant. Also installed via docker compose

```
500
Internal Server Error
Exception at /var/www/html/app/models/PlantsModel.php:213
Reported error: Errorneous file
[Refresh](javascript:void(0);)
Stack trace:
#4 /var/www/html/app/controller/plants.php(151): PlantsModel::addPlant ( 'asd' , '1' , bool(false) , '' , '' )
#3 internal function: PlantsController::add_plant ( Asatru\Controller\ControllerArg )
#2 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/controller.php(575): call_user_func ( array , Asatru\Controller\ControllerArg )
#1 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(118): Asatru\Controller\ControllerHandler::parse ( '/plants/add' )
#0 /var/www/html/public/index.php(26): require_once ( '/var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )
```

**Comment by danielbrendel** [comment]
This error occurs when there is no file uploaded on adding a plant. Did you specify a plant image file? Currently this is mandatory as it serves as a preview image on various occassions. You can specify a PNG (*.png) or JPEG (*.jpg) image.

**Comment by danielbrendel** [comment]
@shroomify-it can you confirm whether this works with using an image when adding a plant (using docker compose when you get the same error as @buzzlightyear88)?

**Comment by buzzlightyear88** [comment]
Got this today when tried with an image, seems like a permissions issue with the directories.
```

Warning: move_uploaded_file(/var/www/html/public/img/8e03da4e31192569d008057b0e24f933.jpg): Failed to open stream: Permission denied in /var/www/html/app/models/PlantsModel.php on line 224

Warning: move_uploaded_file(): Unable to move "/tmp/php0VKiNW" to "/var/www/html/public/img/8e03da4e31192569d008057b0e24f933.jpg" in /var/www/html/app/models/PlantsModel.php on line 224

Warning: exif_imagetype(/var/www/html/public/img/8e03da4e31192569d008057b0e24f933.jpg): Failed to open stream: No such file or directory in /var/www/html/app/modules/UtilsModule.php on line 110

Warning: getimagesize(/var/www/html/public/img/8e03da4e31192569d008057b0e24f933.jpg): Failed to open stream: No such file or directory in /var/www/html/app/modules/UtilsModule.php on line 155

Notice: ob_clean(): Failed to delete buffer. No buffer to delete in /var/www/html/vendor/danielbrendel/asatru-php-framework/src/exception.php on line 25
500
Internal Server Error
Exception at /var/www/html/app/modules/UtilsModule.php:188
Reported error: imagecreatetruecolor(): Argument #1 ($width) must be greater than 0
[Refresh](javascript:void(0);)
Stack trace:
#6 /var/www/html/app/modules/UtilsModule.php(188): imagecreatetruecolor ( double(0) , double(0) )
#5 /var/www/html/app/models/PlantsModel.php(226): UtilsModule::createThumbFile ( '/var/www/html/public/img/8e03da4e31192569d008057b0e24f933.jpg' , NULL , '/var/www/html/public/img/8e03da4e31192569d008057b0e24f933' , 'jpg' )
#4 /var/www/html/app/controller/plants.php(151): PlantsModel::addPlant ( 'boop' , '1' , bool(false) , '' , '' )
#3 internal function: PlantsController::add_plant ( Asatru\Controller\ControllerArg )
#2 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/controller.php(575): call_user_func ( array , Asatru\Controller\ControllerArg )
#1 /var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php(118): Asatru\Controller\ControllerHandler::parse ( '/plants/add' )
#0 /var/www/html/public/index.php(26): require_once ( '/var/www/html/vendor/danielbrendel/asatru-php-framework/src/bootstrap.php' )
```

**Comment by danielbrendel** [comment]
What are your permissions to the /public/img folder? Mine are: drwxr-xr-x
Did you use the current version 1.6 with the same docker environment?

**Comment by danielbrendel** [comment]
@InputObject2 can we modify the following variables in the php.ini?
- upload_max_filesize to 15M
- post_max_size to 15M

In my XAMPP php.ini those values are defaulted by installation at 40M, but I don't believe we need such huge values.

I am not sure how to do that using the docker shell script, but this is something that prevents images from uploading (default is 2M and most images taken with a phone cam are larger).

This should be enough to allow huge images. Then I can investigate further.

**Comment by InputObject2** [comment]
There's no "php.ini" file, but php reads all the files in the `/usr/local/etc/php/conf.d` directory and the default ones in php.ini-production and php.ini-development in `/usr/local/etc/php/`. 

I'm adding the `99-php.ini` to conf.d, if we need to add more overrides they can be put there without anything else changing.

**Comment by inextricable-code** [comment]
I know this is already on your radar, but I'm also getting the same issues as [buzzlightyear88].

**Comment by danielbrendel** [comment]
Meanwhile uploading images in the docker environment works. The .env is another issue where I consider to completely change how settings are stored. 

@InputObject2 is there a good way to allow the app to write the .env file in the project root directory? I would not want to set permissions to the root folder to 755, but then again I am not that familiar with Linux enough to make a good decision.

**Comment by InputObject2** [comment]
I feel like the app shouldn't be writing to the .env file. It also probably should not be 755. We can make one in the startup script with something like `env > .env` but we might as well skip that step and have the app read from the environment directly. 

The file could be a secondary way to set it and users who want it could mount it in a docker volume or pass it to their webserver directly if hosting the old fashioned way.
